'use client';

// app/layout.tsx
import {AppRouterCacheProvider} from '@mui/material-nextjs/v16-appRouter';
import {ThemeProvider} from '@mui/material/styles';
import {Roboto} from 'next/font/google';

import React from "react";
import theme from "@/app/theme";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Box from "@mui/material/Box";
import Sidebar from "@/components/sidebar";
import {AuthProvider, useAuth} from "@/actions/authContext";
import FullScreenLoader from "@/components/fullScreenLoader";
import {RoleEnum} from "@/types/userRole";
import {useMediaQuery} from "@mui/material";

const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-roboto',
});

const AppShell = ({children}: { children: React.ReactNode }) => {
    const {user, logout, loading} = useAuth();
    const isMobile = useMediaQuery(theme.breakpoints.down('md'));

    if (loading) return <FullScreenLoader/>;

    return (
        <>
            <Box sx={{display: 'flex', minHeight: '100vh'}}>
                {user && user?.role ? ( // Authenticated Header
                    <>
                        <Header
                            username={
                                (user.role as RoleEnum) == RoleEnum.ADMIN
                                    ? user.username
                                    : user.lastName
                            }
                            role={user.role}
                            airline={user.airline}
                            workMode={user.workMode}
                            onLogout={logout}
                        />
                        <Sidebar role={user.role} isMobile={isMobile}/>
                    </>
                ) : (
                    <Header/> // Un-authenticated Header
                )}
                <Box
                    component="main"
                    sx={{
                        flexGrow: 1,
                        p: 3,
                        mt: '64px',
                        mx: 'auto',
                        ml: { xs: 'auto', md: 24 },
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                    }}>
                    {children}
                </Box>
            </Box>
            <Footer/>
        </>
    );
}

export default function RootLayout({children}: { children: React.ReactNode; }) {
    return (
        <html lang="en" className={roboto.variable}>
        <body>
        <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
                <AuthProvider>
                    <AppShell>{children}</AppShell>
                </AuthProvider>
            </ThemeProvider>
        </AppRouterCacheProvider>
        </body>
        </html>
    );
}


/*<main style={{
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',}}>
    {children}
</main>
<Box component="main" sx={{flexGrow: 1, p: 3, mt: '64px', ml: '240px'}}>
    {children}
</Box>

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
*/
